#!/usr/bin/env python3
"""Vane Phase 4 - what happens when a policy learns from itself.

Phase 3 fitted a policy on data generated by the incumbent, and stopped. That
is a one-shot experiment, and it hides the failure mode that matters most in
deployment.

A live policy generates the data its own successor will learn from. Because it
quotes near what it currently believes is optimal, the spreads it explores are
narrower than the ones the incumbent explored. Retrain on that, and the support
shrinks again. Iterate, and the model ends up confidently extrapolating in a
region it has stopped observing -- which is precisely the condition that made
the boosted model destroy value in Phase 3.

This script runs that loop explicitly:

    generation 0   fit on incumbent data, wide support
    generation k   deploy, log, refit on what the deployed policy saw

and reports the support width, the true regret, and the realised PnL at each
generation, with and without a floor on exploration. The point is not that the
loop diverges dramatically -- with a well-specified model it may not -- but
that the *support* provably collapses, and that whether that collapse hurts
depends on a modelling choice nobody would notice from a one-shot experiment.

    python3 analysis/run_phase4.py --generations 5
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

from export_model import export  # noqa: E402
from vane_data import load, time_split  # noqa: E402
from vane_demand import LogisticDemand, evaluate  # noqa: E402
from vane_policy import oracle_regret, optimal_spread  # noqa: E402
from vane_support import optimal_spread_in_support, support_bounds  # noqa: E402

FMT = lambda x: f"{x:9.2f}"  # noqa: E731


def simulate(out_prefix: Path, weeks: int, seed: int, jitter: float,
             model: Path | None) -> None:
    """Run the C++ simulator, optionally with a learned policy driving it."""
    cmd = [
        str(ROOT / "build/vane-sim"), "--weeks", str(weeks), "--seed", str(seed),
        "--jitter", str(jitter), "--out", str(out_prefix),
    ]
    if model is not None:
        cmd += ["--model", str(model)]
    subprocess.run(cmd, check=True, capture_output=True)


def measure(prefix: Path) -> dict:
    """Score a logged run against the truth, and describe its spread support."""
    ds = load(str(prefix))
    tr, te = time_split(ds, 0.7)
    y = tr.events["accepted"].to_numpy()

    model = LogisticDemand().fit(tr.events, y)
    bounds = support_bounds(tr.events)
    pol = optimal_spread_in_support(model, te.events, bounds)
    reg = oracle_regret(te.events, te.oracle, pol)
    fit = evaluate(model, te.events, te.events["accepted"].to_numpy())

    r_lo, r_hi = bounds["retail"]
    retail = ds.events[ds.events["tier"] == "retail"]["quoted_half_bps"]

    return {
        "events": len(ds),
        "retail_support_lo": r_lo,
        "retail_support_hi": r_hi,
        "retail_support_width": r_hi - r_lo,
        "retail_spread_sd": float(retail.std()),
        "retail_spread_mean": float(retail.mean()),
        "brier": fit["brier"],
        "ece": fit["ece"],
        "regret_logged": reg["regret_logged"],
        "regret_policy": reg["regret_target"],
        "hit_rate": float(ds.events["accepted"].mean()),
    }


def run_loop(generations: int, weeks: int, seed: int, jitter: float,
             floor_jitter: float | None, tag: str) -> pd.DataFrame:
    """One closed-loop run. `floor_jitter` keeps a minimum of exploration."""
    data_dir = ROOT / "data/loop"
    model_dir = ROOT / "models/loop"
    data_dir.mkdir(parents=True, exist_ok=True)
    model_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    model_path: Path | None = None

    for gen in range(generations):
        prefix = data_dir / f"{tag}_g{gen}"
        # Generation 0 is the incumbent: no learned policy, full exploration.
        j = jitter if gen == 0 else (floor_jitter if floor_jitter is not None else jitter)
        simulate(prefix, weeks, seed + gen, j, model_path)

        m = measure(prefix)
        m["generation"] = gen
        m["tag"] = tag
        m["jitter"] = j
        rows.append(m)

        # Fit the policy that will generate the next generation's data.
        model_path = model_dir / f"{tag}_g{gen}.txt"
        export(str(prefix), str(model_path))

    return pd.DataFrame(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generations", type=int, default=5)
    ap.add_argument("--weeks", type=int, default=10)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--jitter", type=float, default=0.22)
    ap.add_argument("--floor", type=float, default=0.22,
                    help="exploration floor once a learned policy is deployed")
    ap.add_argument("--decay", type=float, default=0.04,
                    help="the 'exploitation' arm: exploration decays to this")
    args = ap.parse_args()

    if not (ROOT / "build/vane-sim").exists():
        raise SystemExit("build/vane-sim not found; run make first")

    print("closed loop: each generation trains on the data the previous one produced\n")

    decayed = run_loop(args.generations, args.weeks, args.seed, args.jitter,
                       args.decay, "decay")
    held = run_loop(args.generations, args.weeks, args.seed, args.jitter,
                    args.floor, "floor")

    cols = ["generation", "jitter", "retail_support_lo", "retail_support_hi",
            "retail_support_width", "retail_spread_sd", "brier", "ece",
            "regret_logged", "regret_policy"]

    print("A. exploration decays after deployment (the natural thing to do)")
    print(decayed[cols].to_string(index=False, float_format=FMT))
    print("\nB. exploration held at a floor (the fix)")
    print(held[cols].to_string(index=False, float_format=FMT))

    print("\nsupport width, retail (bps):")
    for gen in range(args.generations):
        a = decayed.loc[decayed.generation == gen, "retail_support_width"].iloc[0]
        b = held.loc[held.generation == gen, "retail_support_width"].iloc[0]
        bar_a = "#" * int(a / 4)
        print(f"  gen {gen}   decayed {a:6.1f} {bar_a:<52s} held {b:6.1f}")

    d0 = decayed.iloc[0]["retail_support_width"]
    dn = decayed.iloc[-1]["retail_support_width"]
    h0 = held.iloc[0]["retail_support_width"]
    hn = held.iloc[-1]["retail_support_width"]
    print(f"\n  decayed: {d0:.1f} -> {dn:.1f} bps  ({100*(dn/d0-1):+.1f}%)")
    print(f"  held   : {h0:.1f} -> {hn:.1f} bps  ({100*(hn/h0-1):+.1f}%)")

    out = ROOT / "data/phase4_loop.csv"
    pd.concat([decayed, held]).to_csv(out, index=False)
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
