"""Vane Phase 3 - turning a demand model into a price, and scoring it honestly.

Two separate problems live here.

**Choosing the price.** Given P(accept | spread, context), the revenue-maximising
quote solves

    max over delta of   (delta - cost) * P(accept | delta, x)

subject to the same tier floors and ceilings the Phase 1 engine enforces. There
is no closed form once the demand model is nonparametric, so this is a grid
search over log-spread, refined locally. The grid is defensible precisely
because monotonicity is enforced in the model: the objective is the product of
an increasing linear term and a non-increasing probability, so it has a single
interior peak.

**Scoring the price.** This is the hard part, and the reason the phase exists.
The logged data was generated by the incumbent policy plus jitter. A new policy
proposes different spreads, and for those we have no outcomes at all. Comparing
"revenue the new policy would have made" against "revenue the old policy did
make" by simply plugging the new spreads into the model is circular: it scores
the policy using the very model that chose it, so a confidently wrong model
looks brilliant.

Three estimators, in increasing order of trustworthiness:

  direct        - plug the new spread into the demand model. Circular, but
                  cheap, and a useful upper reference.
  IPS / SNIPS   - reweight the *logged outcomes* by how likely the new policy
                  was to have chosen the logged action. Uses no model of the
                  outcome, so it is unbiased, but the weights explode when the
                  policies disagree. SNIPS self-normalises to tame that.
  doubly robust - combine the two: model prediction plus importance-weighted
                  residual. Correct if *either* the model or the propensities
                  are right.

The simulator also knows the true optimum, so `oracle_regret` reports what the
off-policy estimators cannot: the actual gap to the best attainable price. That
number is the honest scorecard, and it exists only because this is a simulation.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from vane_data import TIERS

# The commercial bands from the Phase 1 pricing config, mirrored here so the
# learned policy is held to exactly the same limits as the incumbent.
TIER_BANDS = {
    "retail":    (40.0, 400.0),
    "corporate": (20.0, 220.0),
    "private":   (15.0, 140.0),
    "wealth":    (12.0, 90.0),
}
COST_FLOOR_BPS = 12.0


@dataclass
class PolicyResult:
    spreads: np.ndarray          # the half-spread this policy would quote, bps
    expected_accept: np.ndarray  # model's P(accept) at that spread
    expected_margin: np.ndarray  # (spread - cost) * P(accept)


def clamp_to_band(spreads: np.ndarray, tier: pd.Series, cost_bps: float) -> np.ndarray:
    lo = tier.map(lambda t: TIER_BANDS[t][0]).to_numpy(dtype=float)
    hi = tier.map(lambda t: TIER_BANDS[t][1]).to_numpy(dtype=float)
    lo = np.maximum(lo, max(COST_FLOOR_BPS, cost_bps))
    return np.clip(spreads, lo, hi)


def optimal_spread(
    model,
    df: pd.DataFrame,
    cost_bps: float = 1.5,
    grid: int = 96,
    refine: int = 3,
) -> PolicyResult:
    """Revenue-maximising quote per row, by grid search then local refinement.

    Vectorised across rows: each grid point is one batched model call, so this
    costs `grid + refine*8` predictions in total rather than one per row.
    """
    n = len(df)
    lo = np.full(n, max(COST_FLOOR_BPS, cost_bps) * 1.01)
    hi = np.full(n, 600.0)

    best_d = lo.copy()
    best_v = np.full(n, -np.inf)

    def scan(lo_, hi_, k):
        nonlocal best_d, best_v
        for i in range(k):
            frac = i / (k - 1)
            d = np.exp(np.log(lo_) + frac * (np.log(hi_) - np.log(lo_)))
            p = model.predict_proba(df, spread=d)
            v = (d - cost_bps) * p
            better = v > best_v
            best_v = np.where(better, v, best_v)
            best_d = np.where(better, d, best_d)

    scan(lo, hi, grid)
    # Local refinement around the incumbent best, shrinking the bracket.
    width = (np.log(hi) - np.log(lo)) / (grid - 1)
    for _ in range(refine):
        lo_r = np.exp(np.log(best_d) - width)
        hi_r = np.exp(np.log(best_d) + width)
        scan(np.maximum(lo_r, lo), np.minimum(hi_r, hi), 12)
        width /= 4.0

    spreads = clamp_to_band(best_d, df["tier"], cost_bps)
    p = model.predict_proba(df, spread=spreads)
    return PolicyResult(spreads, p, (spreads - cost_bps) * p)


def static_policy(df: pd.DataFrame, cost_bps: float = 1.5) -> PolicyResult:
    """The incumbent: whatever the Phase 1 engine actually quoted, jitter aside."""
    spreads = df["base_half_bps"].to_numpy(dtype=float)
    return PolicyResult(spreads, np.full(len(df), np.nan), np.full(len(df), np.nan))


# ---------------------------------------------------------------------------
# off-policy evaluation
# ---------------------------------------------------------------------------
def _log_importance_weight(
    target_spread: np.ndarray, df: pd.DataFrame, sigma: float
) -> np.ndarray:
    """Log importance weight of the logged action under the target policy.

    Both policies are smoothed log-normals over the same action variable, the
    quoted half-spread. The behaviour policy centred on `base_half_bps` with
    width `jitter_log_sd`; the target centres on its own chosen spread. The
    weight is the ratio of the two densities evaluated at the *logged* action.

    Getting the coordinates wrong here is easy and silent. An earlier version
    compared the target's density in log-spread against the behaviour policy's
    density in log-*multiplier*. Those differ by the (row-varying) location
    `log(base_half_bps)`, so a target that reproduced the behaviour policy
    exactly received weights of peak/density rather than 1, and SNIPS came back
    7% low on a case whose answer was known. The identity test below is what
    caught it, and it is why that test exists.
    """
    logged = np.log(df["quoted_half_bps"].to_numpy(dtype=float))
    base = np.log(np.maximum(df["base_half_bps"].to_numpy(dtype=float), 1e-9))
    sd_b = df["jitter_log_sd"].to_numpy(dtype=float)
    sd_b = np.where(sd_b > 0, sd_b, sigma)

    mu_t = np.log(np.maximum(target_spread, 1e-9))

    log_p_target = -0.5 * ((logged - mu_t) / sigma) ** 2 - np.log(sigma * np.sqrt(2 * np.pi))
    log_p_behav = -0.5 * ((logged - base) / sd_b) ** 2 - np.log(sd_b * np.sqrt(2 * np.pi))
    return log_p_target - log_p_behav


def off_policy_value(
    df: pd.DataFrame,
    target: PolicyResult,
    model=None,
    cost_bps: float = 1.5,
    sigma: float | None = None,
    clip: float = 20.0,
) -> dict:
    """Estimate the per-event margin the target policy would have earned.

    A deterministic target assigns zero probability to almost every logged
    action, which makes importance weights degenerate. The target is therefore
    smoothed by the same log-normal width the behaviour policy used, so what is
    evaluated is a slightly stochastic version of the policy. That is the
    standard treatment for continuous actions, and it is stated rather than
    hidden.

    Returns the direct, IPS, SNIPS and doubly-robust estimates in bps per unit
    of notional, together with the effective sample size of the weights, which
    is the honest measure of how far the target has drifted from the data.
    """
    y = df["accepted"].to_numpy(dtype=float)
    logged_spread = df["quoted_half_bps"].to_numpy(dtype=float)
    if sigma is None:
        sigma = float(np.median(df["jitter_log_sd"].to_numpy()))
        if sigma <= 0:
            sigma = 0.2

    # Realised margin under the behaviour policy: what actually happened.
    behaviour = float(np.mean((logged_spread - cost_bps) * y))

    # Importance weights: target density over behaviour density, both in log
    # space over the same action variable.
    log_w = _log_importance_weight(target.spreads, df, sigma)
    w = np.exp(np.clip(log_w, -50, np.log(clip)))
    w = np.minimum(w, clip)

    reward = (logged_spread - cost_bps) * y
    ips = float(np.mean(w * reward))
    snips = float(np.sum(w * reward) / max(np.sum(w), 1e-12))
    ess = float(np.sum(w) ** 2 / max(np.sum(w**2), 1e-12))

    out = {
        "behaviour": behaviour,
        "ips": ips,
        "snips": snips,
        "ess": ess,
        "ess_frac": ess / len(df),
        "mean_weight": float(np.mean(w)),
        "max_weight": float(np.max(w)),
        "sigma": sigma,
    }

    if model is not None:
        direct = float(np.mean(target.expected_margin))
        # Doubly robust: model's estimate at the target action, corrected by the
        # importance-weighted residual at the logged action.
        q_logged = model.predict_proba(df) * (logged_spread - cost_bps)
        dr = float(np.mean(target.expected_margin + w * (reward - q_logged)))
        out["direct"] = direct
        out["dr"] = dr
    return out


def oracle_regret(df: pd.DataFrame, oracle: pd.DataFrame, target: PolicyResult) -> dict:
    """The truth, available only because this is a simulation.

    Recomputes expected margin under the *true* demand curve at the spread the
    target policy chose, and compares it to the true optimum.
    """
    mu = oracle["mu"].to_numpy()
    s = oracle["sigma_ln"].to_numpy()
    cost = 1.5

    def true_margin(delta):
        from scipy.stats import norm

        p = norm.cdf((mu - np.log(np.maximum(delta, 1e-9))) / s)
        return np.maximum(delta - cost, 0.0) * p

    best = oracle["oracle_margin_bps"].to_numpy()
    got = true_margin(target.spreads)
    logged = true_margin(df["quoted_half_bps"].to_numpy(dtype=float))

    return {
        "true_margin_target": float(np.mean(got)),
        "true_margin_logged": float(np.mean(logged)),
        "true_margin_oracle": float(np.mean(best)),
        "regret_target": float(np.mean(best - got)),
        "regret_logged": float(np.mean(best - logged)),
        "regret_reduction": float(
            1.0 - np.mean(best - got) / max(np.mean(best - logged), 1e-12)
        ),
    }


def by_tier(df: pd.DataFrame, oracle: pd.DataFrame, target: PolicyResult) -> pd.DataFrame:
    rows = []
    for t in TIERS:
        m = (df["tier"] == t).to_numpy()
        if not m.any():
            continue
        r = oracle_regret(df[m], oracle[m], PolicyResult(
            target.spreads[m], target.expected_accept[m], target.expected_margin[m]
        ))
        rows.append({
            "tier": t,
            "n": int(m.sum()),
            "logged_bps": float(df.loc[m, "quoted_half_bps"].mean()),
            "learned_bps": float(target.spreads[m].mean()),
            "oracle_bps": float(oracle.loc[m, "oracle_half_bps"].mean()),
            "margin_logged": r["true_margin_logged"],
            "margin_learned": r["true_margin_target"],
            "margin_best": r["true_margin_oracle"],
            "regret_logged": r["regret_logged"],
            "regret_learned": r["regret_target"],
        })
    return pd.DataFrame(rows)
